

data = {'id': 'cat',
        'amount_tsh': 'num',
        'date_recorded': 'cat',
        'funder': 'cat',
        'gps_height': 'num',
        'installer': 'cat',
        'longitude': 'num',
        'latitude': 'num',
        'wpt_name': 'cat',
        'num_private': 'cat',
        'basin': 'cat',
        'subvillage': 'cat',
        'region': 'cat',
        'region_code': 'cat',
        'district_code': 'cat',
        'lga': 'cat',
        'ward': 'cat',
        'population': 'num',
        'public_meeting': 'cat',
        'recorded_by': 'cat',
        'scheme_management': 'cat',
        'scheme_name': 'cat',
        'permit': 'cat',
        'construction_year': 'cat',
        'extraction_type': 'cat',
        'extraction_type_group': 'cat',
        'extraction_type_class': 'cat',
        'management': 'cat',
        'management_group': 'cat',
        'payment': 'cat',
        'payment_type': 'cat',
        'water_quality': 'cat',
        'quality_group': 'cat',
        'quantity': 'cat',
        'quantity_group': 'cat',
        'source': 'cat',
        'source_type': 'cat',
        'source_class': 'cat',
        'waterpoint_type': 'cat',
        'waterpoint_type_group': 'cat',

        # missing columns
        'missing_funder': 'cat',
        'missing_installer': 'cat',
        'missing_subvillage': 'cat',
        'missing_public_meeting': 'cat',
        'missing_scheme_management': 'cat',
        'missing_scheme_name': 'cat',
        'missing_permit': 'cat',
        'total_missing': 'num',

        # kmeans
        'kmeans_lat_long': 'cat',

        # dates
        'year': 'cat',
        'month': 'cat',
        'day': 'cat'}
