
target_mapping = {'functional':0,
                  'functional needs repair':1,
                  'non functional':2}

data = {'id': 'cat',
        'amount_tsh': 'num',
        'date_recorded': 'cat',
        'funder': 'cat',
        'gps_height': 'num',
        'installer': 'cat',
        'longitude': 'num',
        'latitude': 'num',
        'wpt_name': 'cat',
        'num_private': 'cat',
        'basin': 'cat',
        'subvillage': 'cat',
        'region': 'cat',
        'region_code': 'cat',
        'district_code': 'cat',
        'lga': 'cat',
        'ward': 'cat',
        'population': 'num',
        'public_meeting': 'cat',
        'recorded_by': 'cat',
        'scheme_management': 'cat',
        'scheme_name': 'cat',
        'permit': 'cat',
        'construction_year': 'cat',
        'extraction_type': 'cat',
        'extraction_type_group': 'cat',
        'extraction_type_class': 'cat',
        'management': 'cat',
        'management_group': 'cat',
        'payment': 'cat',
        'payment_type': 'cat',
        'water_quality': 'cat',
        'quality_group': 'cat',
        'quantity': 'cat',
        'quantity_group': 'cat',
        'source': 'cat',
        'source_type': 'cat',
        'source_class': 'cat',
        'waterpoint_type': 'cat',
        'waterpoint_type_group': 'cat',

        # missing columns
        'missing_funder': 'cat',
        'missing_installer': 'cat',
        'missing_subvillage': 'cat',
        'missing_public_meeting': 'cat',
        'missing_scheme_management': 'cat',
        'missing_scheme_name': 'cat',
        'missing_permit': 'cat',
        'total_missing': 'num',

        # kmeans
        'kmeans_lat_long': 'cat',

        # dates
        'year': 'cat',
        'month': 'cat',
        'day': 'cat',
        'day_week': 'cat'
        }

data_card = {'date_recorded': 50,
             'funder': 50,
             'installer': 50,
             'wpt_name': 50,
             'num_private': 50}

data_card1 = {'date_recorded': 50,
             'funder': 50,
             'installer': 50,
             'wpt_name': 50,
             'num_private': 50,
             'basin': 9,
             'subvillage': 50,
             'region': 21,
             'region_code': 20,
             'district_code': 20,
             'lga': 50,
             'ward': 50,
             'public_meeting': 2,
             'scheme_management': 12,
             'scheme_name': 50,
             'permit': 2,
             'construction_year': 50,
             'extraction_type': 18,
             'extraction_type_group': 13,
             'extraction_type_class': 7,
             'management': 12,
             'management_group': 5,
             'payment': 7,
             'payment_type': 7,
             'water_quality': 8,
             'quality_group': 5,
             'quantity': 5,
             'quantity_group': 5,
             'source': 10,
             'source_type': 7,
             'source_class': 3,
             'waterpoint_type': 7,
             'waterpoint_type_group': 6,

             # missing columns
             'missing_funder': 2,
             'missing_installer': 2,
             'missing_subvillage': 2,
             'missing_public_meeting': 2,
             'missing_scheme_management': 2,
             'missing_scheme_name': 2,
             'missing_permit': 2,

             # kmeans
             'kmeans_lat_long': 5,

             # dates
             'year': 6,
             'month': 12,
             'day': 30,
             'day_week': 7
             }
